# Generated by Django 5.1.1 on 2026-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
